use_frameworks!

platform :ios, '8.0'

target 'HotFixDZNEmptyDataSet_Example' do
  pod 'HotFixDZNEmptyDataSet', :path => '../'

  target 'HotFixDZNEmptyDataSet_Tests' do
    inherit! :search_paths

    
  end
end
